#!/bin/bash

# FeMIP will remap desired model file(s) to a 1x1 regular horizontal grid with a vertical
# grid corresponding to the WOA01 (default) or a custom vertical grid (refer to makegrid).
# If you wish to use a custom grid, run makegrid before FeMIP else this will generate an error.
# The FeMIP script uses CDO and thus requires that certain variables and attributes, such as 
# longitude and latitude, be in a specific format. Refer to README.txt for some useful CDO and 
# NCO processing commands, else refer to CDO documentation at https://code.mpimet.mpg.de/projects/cdo/embedded/cdo.pdf
# 
# FeMIP requires the user to specify the file(s) to be processed as well as the vertical grid of choice
#
# Written by Jonathan J Rogerson
# 25 February 2020
# Edited 5 December 2020

MYGRID=false          # Set MYGRID to true if you wish to use your custom grid created by 'makegrid'
INDIR="../MODEL_DATA" # Directory of model files to be processed
EXDIR="../OUTPUTS" # Location where output directory will be created
OUTDIR="$EXDIR/FeMIP_01_nearest_interpolation" # Output directory

cd $INDIR
FILES=`ls UKSEM.nc`            # Specify the file(s) to be processed

##############################
#	END USER INPUTS
##############################
LONLAT="-180,180,-90,90"
GRID="r360x180"
TEMPLATE="template_FeMIP_01"
mkdir $OUTDIR	         	# Create directory where processed files will go
# Create a once-off horizontal gridding template

cdo -f nc -sellonlatbox,$LONLAT -random,$GRID $TEMPLATE.nc

if [ "$MYGRID" = true ] ; then

# Use the mygrid file

  read line < depth
  numbers=($line)
  LEVELS="$numbers"
  cp ./mygrid $OUTDIR/
  chmod 755 mygrid

else

# Create the WOA01 vertical grid

LEVELS="5,10,20,30,50,75,100,125,150,200,250,300,400,500,600,700,800,900,1000,1100,1200,1300,1400,1500,1750,2000,2500,3000,3500,4000,4500,5000,5500"
cat > WOA01 << EOR
zaxistype = depth_below_sea
size = 33
units = m
levels = 0 10 20 30 50 75 100 125 150 200 250 300 400 500 600 700 800 900 1000 1100 1200 1300 1400 1500 1750 2000 2500 3000 3500 4000 4500 5000 5500
EOR
  cp ./WOA01 $OUTDIR/
  chmod 755 WOA01

fi
  
for f in $FILES
do
  echo $f
  cdo -f nc remapnn,$TEMPLATE.nc -intlevel,$LEVELS $f $OUTDIR/$f
  if [ "$MYGRID" = true ] ; then
    cdo -f nc setzaxis,mygrid $OUTDIR/$f $OUTDIR/FeMIP_$f           # Loop over the file(s) and do the interpolation
    mv $INDIR/levels $OUTDIR/
  else
    cdo -f nc setzaxis,WOA01 $OUTDIR/$f $OUTDIR/FeMIP_$f
   fi
  rm $OUTDIR/$f
done

echo "ALL done"


